### ISSUE TITLE
Make the Individual's BU accessible

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Identities#6]
This will be used for filtering queries.
Preferably in the token.

**Comment by baddlan** [comment]
https://github.com/DigitalState/Identities/issues/6

**Comment by marioprudhomme** [comment]
Done. deaef8b64f2468b419c7ae2a29678d3f7668a018

At the moment, doing a GET /individuals/uuid will get the BU memberships. 

One potential issue of storing it in the token is if the membership changes, the token needs to be re-created. Thoughts?

**Comment by marioprudhomme** [comment]
The concept was abandoned in favor of adding a server-side doctrine orm query extension.
